### PR TITLE
updated lib/index.js

### PR DESCRIPTION
**Pull request by lambtron**
added 'client' to channel

@sperand-io @hankim813

### CODE REVIEW

**Comment by joluet** [comment]
Will this allow identify calls coming from the JavaScript client to come through to Appboy?

**Comment by lambtron** [comment]
@joluet correct! Now calls made from our analytics.js library will be sent through the server to Appboy.

**Comment by f2prateek** [comment]
LGTM

**Comment by joluet** [comment]
Great, thank you guys! :+1:

**Pull request merged**
