### PR TITLE
allow more gender options, case insensitive

### PR DESCRIPTION
**Pull request by prestonwrthompson**

### CODE REVIEW

**Comment by prestonwrthompson** [comment]
@amillet89 Let me know when you or someone from the Segment team will have a chance to look at this. Appreciate it.

**Comment by f2prateek** [comment]
I don't think our spec documents this currently, but `traits.gender` will always be one of these values so you shouldn't need to check for it.

**Comment by ndhoule** [comment]
@f2prateek we don't/won't prescribe genders in the spec because not everyone self-identifies as one of these genders

**Comment by f2prateek** [comment]
So what happens if Flurry expects `M` but AppBoy expects `Male` (I see this PR makes it accept `M` as well, but it's easy to see that not all integrations will do this)? Users wouldn't be able to send that information to both integrations with one API call.

**Comment by prestonwrthompson** [comment]
any update here guys?

**Comment by f2prateek** [comment]
@prestonwrthompson sorry for the delay. We've discussed this and gender will always be in lowercase, e.g. `female`, `pangender`. Since AppBoy is only interesting in grouping those by male, female and other, the code would look something like this:

```js
if (traits.gender != 'female' && traits.gender != 'male') {
     traits.gender = 'other'
}
```

**Comment by prestonwrthompson** [comment]
What if someone sends something like ```m``` or ```man```? Can I expect that to be converted to ```male``` before it is sent?

**Comment by f2prateek** [comment]
We're adding this to our spec, but in general spec'd fields are documented to indicating that we accept them in a certain format. In this case we'll document that users  should always send gender a complete string (not just `m` or `f`) in lowercase.

**Comment by f2prateek** [comment]
@prestonwrthompson Thanks for the PR, we'll accept this for backwards compatibility for now!

**Comment by prestonwrthompson** [comment]
Sounds good, thanks for the help!

**Comment by f2prateek** [comment]
@prestonwrthompson Could you rebase against master? You're on a stale version and this line in particular - https://github.com/prestonwrthompson/integration - https://github.com/segmentio/integration-appboy/blob/force-ci/test/index.js#L5 - cases the build to fail. 

I did try without that line and it builds but tests are breaking -https://cloudup.com/c9zqFT-CyrT. Let me know when you can fix them and we can merge this PR.

**Comment by prestonwrthompson** [comment]
@f2prateek all the test passed for me just now, let me know if it works for you

**Comment by prestonwrthompson** [comment]
@f2prateek any update?

**Comment by prestonwrthompson** [comment]
thanks

**Comment by f2prateek** [comment]
Sorry for the delay, this just fell of my radar. Thanks for the fix!

**Comment by prestonwrthompson** [comment]
No worries, thanks for taking the time to review

**Pull request merged**
